version: "3.5"
services:
  lint:
    image: buildkite/plugin-linter
    command: ['--id', 'hasura/smooth-checkout']
    volumes:
      - .:/plugin:ro
  lint-shellcheck:
    image: koalaman/shellcheck:stable
    command: ["hooks/*"]
    volumes:
      - .:/mnt:ro
  tests:
    image: buildkite/plugin-tester
    volumes:
      - .:/plugin:ro
